# Generated by Django 2.1.4 on 2018-12-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181226_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='title', max_length=1100, unique_for_date='created'),
        ),
    ]
