# Generated by Django 2.1.4 on 2018-12-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181226_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.BooleanField(default=True),
        ),
    ]
